[package]
name = "copo"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[[bin]]
name = "copo"
path = "./src/main.rs"
